### PR TITLE
BS-B-1-Refactoring

### LINKED ISSUE #7: BS-B-1-Refactoring
- Added annotation "CurentUser"
- Add new ExceptionHandler
- Refactroing entities

### PR DESCRIPTION
**Pull request by pro100user15**
# Releted Issue
- closed #7 

# Proposed Changes
- Added annotation "CurentUser"
- Add new ExceptionHandler
- Refactroing entities

# Additional Info
- 

# Checklist
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

File: bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java [hunk 1]
```diff
@@ -13,20 +13,20 @@
 @Mapper
 public interface CategoryMapper {
 
-    @Named("countBooks")
+    /*@Named("countBooks")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java:16]: avoid committing commented code

File: bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java [hunk 2]
```diff
@@ -13,20 +13,20 @@
...
+    }*/
 
     Category toCategory(CategoryDTO categoryDTO);
 
     CategoryDTO toCategoryDTO(Category category);
 
     List<CategoryDTO> toCategoryDTOList(List<Category> categories);
 
-    @Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
+    //@Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java:27]: avoid committing commented code

File: bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java [hunk 3]
```diff
@@ -13,20 +13,20 @@
...
     CategoryWithBooksDTO toCategoryWithBooksDTO(Category category);
 
-    @Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
+    //@Mapping(source = "books", target = "countBooks", qualifiedByName = "countBooks")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/mapper/CategoryMapper.java:30]: avoid committing commented code

File: bookstore-backend/src/main/java/com/pro100user/bookstore/model/Book.java [hunk 4]
```diff
@@ -71,7 +73,7 @@
 
     @NotNull
     @Column(nullable = false)
-    @Max(value = 2022, message = "Publication year cannot be higher than 2022")
+    //@PastOrPresent(message = "Publication year cannot be higher than the current year")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/model/Book.java:76]: I won't stop writing this until you stop committing commented code, this isn't acceptable within PRs unless there is a reason (which is clearly stated)

File: bookstore-backend/src/main/java/com/pro100user/bookstore/model/Category.java [hunk 5]
```diff
@@ -24,12 +21,12 @@
...
     @NotNull
-    @Size(min = 2, max = 32, message = "Category must be between 2 and 32 characters long")
-    @Column(length = 32, nullable = false, unique = true)
+    @Size(min = 2, max = 64, message = "Category must be between 2 and 64 characters long")
+    @Column(length = 64, nullable = false, unique = true)
     @NotEmpty(message = "Category cannot be empty")
     private String name;
 
+
     @OneToMany(mappedBy = "category")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/model/Category.java:30]: be consistent, if you explicitly state the fetch type LAZY for *ToMany annotations (even though it's the default fetch type), then follow this rule everywhere

File: bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java [hunk 6]
```diff
@@ -6,39 +6,40 @@
...
+    @Size(min = 2, max = 64, message = "Surname must be between 2 and 64 characters long")
+    @Column(length = 64)
     @NotEmpty(message = "Surname cannot be empty")
     private String surname;
 
     @NotNull
     @Email(message = "Email must match format")
-    @Size(min = 5, max = 40, message = "Email must be between 5 and 40 characters long")
-    @Column(unique = true, length = 40, nullable = false)
+    @Size(min = 3, max = 320, message = "Email must be between 3 and 320 characters long")
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/model/User.java:41]: email can be 320 characters long while name and surname - 64, this is not fair :)

File: bookstore-backend/src/main/java/com/pro100user/bookstore/security/jwt/JwtProvider.java [hunk 7]
```diff
@@ -50,9 +50,8 @@ public boolean validateToken(String token) {
             Jwts.parser().setSigningKey(jwtSecret).parseClaimsJws(token);
             return true;
         } catch (Exception e) {
-            log.warn("invalid token");
+            throw new JwtAuthenticationException("Jwt is valid!");
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/security/jwt/JwtProvider.java:53]: I suppose it should be "invalid" or "is not valid", shouldn't it?

File: bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/CategoryServiceImpl.java [hunk 8]
```diff
@@ -4,23 +4,22 @@
...
 import org.springframework.transaction.annotation.Propagation;
 import org.springframework.transaction.annotation.Transactional;
 
-import java.util.ArrayList;
 import java.util.List;
+import java.util.stream.Collectors;
 
-@Transactional(propagation = Propagation.REQUIRES_NEW)
 @Service
+@Transactional(propagation = Propagation.REQUIRES_NEW)
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/CategoryServiceImpl.java:17]: not consistent with other services

File: bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/UserServiceImpl.java [hunk 9]
```diff
@@ -41,9 +37,10 @@ public User readById(Long id) {
     }
 
     @Override
-    public User update(User object) {
-        readById(object.getId());
-        return userRepository.update(object);
+    public User update(User user) {
+        User oldUser = readById(user.getId());
```
Comment (dshma) [inline bookstore-backend/src/main/java/com/pro100user/bookstore/service/impl/UserServiceImpl.java:41]: unused variable

**Review by dshma — CHANGES_REQUESTED** [review]

File: bookstore-backend/src/main/java/com/pro100user/bookstore/controller/MainController.java [hunk 10]
```diff
@@ -10,10 +10,6 @@
 @RequestMapping("/")
 public class MainController {
 
-    public MainController() {
-        System.out.println("======================================");
-    }
-
     @GetMapping
```
[the remark this answers is not in the document]
Comment (pro100user15) [reply bookstore-backend/src/main/java/com/pro100user/bookstore/controller/MainController.java:13]: We checked at what point the controllers are configured, because in one they were not configured.
This designer has already taken away
